dataset:
  # annotations: /path/to/annotations/
  # dataset: /path/to/dataset
  targets:
    - move
    - zoom
    - rorateX
    - rorateY
    - rorateZ
    - release
    - no_gesture
  image_size: [224, 224]
  subset: -1
random_state: 42
device: 'cuda'
experiment_name: MobileNetV3_large
model:
  name: 'MobileNetV3_large'  # 'MobileNetV3_large' or 'MobileNetV3_small' or 'ResNet18'
  pretrained: False
  freezed: False
  start_epoch: 0
  checkpoint: ../output/MobileNetV3_large_pretrain.pt
  full_frame: False
optimizer:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 25
  num_workers: 16
  train_batch_size: 128
  test_batch_size: 128
  prefetch_factor: 16
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
